pipeline {
    agent any

    stages {
        stage('Clonar Repositorio') {
            steps {
                git branch: 'main', url: 'https://github.com/JoanLleo/pps10485285.git'
            }
        }

        stage('Moverse a la carpeta del proyecto') {
            steps {
                dir('RA5/RA5_1/3.1/T1') {
                    echo 'En la carpeta del proyecto'
                }
            }
        }

        stage('Instalar Dependencias') {
            steps {
                dir('RA5/RA5_1/3.1/T1') {
                    sh 'python3 -m venv venv && . venv/bin/activate && pip install --upgrade pip'
                }
            }
        }

        stage('Ejecutar Pruebas') {
            steps {
                dir('RA5/RA5_1/3.1/T1') {
                    sh '. venv/bin/activate && python -m unittest discover -s . -p "test_*.py"'
                }
            }
        }
    }

    post {
        success {
            echo '✅ Todas las etapas se completaron correctamente.'
        }
        failure {
            echo '❌ Ocurrió un error en la canalización.'
        }
    }
}
