Vagrant.configure("2") do |config|
  config.vm.box = "BaseBox-lleo/UbuntuServer24-04"
  config.vm.box_version = "1"

  # Evitar el inicio automático de la VM
  config.vm.provider "virtualbox" do |vb|
    vb.name = "UbuntuServer24-04-Terraform"
    vb.memory = 2048
    vb.cpus = 2
    vb.gui = false  # No abrir la GUI de VirtualBox
  end

  # Evitar que Vagrant intente conectarse a la VM a través de SSH
  config.ssh.insert_key = false

  # Prevenir la ejecución de cualquier script de provisión
  config.vm.provision :shell, inline: "exit 0"
end
